AWSTemplateFormatVersion: '2010-09-09'

Resources:
  DatabaseSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: 'Hindsite database credentials'
      GenerateSecretString:
        SecretStringTemplate: '{"username": "hindsite"}'
        GenerateStringKey: 'password'
        PasswordLength: 16
        ExcludeCharacters: '"@/\'

Outputs:
  DatabaseSecret:
    Value: !Ref "DatabaseSecret"